### ISSUE TITLE
Failed when launch locally

### ISSUE THREAD

**Issue by alexander-myltsev** [OlegIlyenko/graphql-toolbox#11]
Hi,

Having

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C67)
      Kernel Version: Darwin 16.3.0
$ npm -v
4.3.0
$ sbt sbtVersion
[info] 0.13.11
```

I have error as follows:

```
sbt run     
[info] Loading global plugins from /Users/user/.sbt/0.13/plugins
[info] Loading project definition from /Users/user/projects/project/tmp/graphql-toolbox/project
[info] Set current project to graphql-toolbox (in build file:/Users/user/projects/project/tmp/graphql-toolbox/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

Hash: 26a367041ad92332d98f
Version: webpack 1.12.13
Time: 19195ms
           Asset      Size  Chunks             Chunk Names
   format.js.map   4.02 MB       0  [emitted]  format
       format.js   3.36 MB       0  [emitted]  format
        index.js    345 kB       2  [emitted]  index
        proxy.js   3.73 MB       3  [emitted]  proxy
      format.css   37.9 kB       0  [emitted]  format
    graphiql.css   32.8 kB       1  [emitted]  graphiql
       index.css    106 kB       2  [emitted]  index
       proxy.css   40.1 kB       3  [emitted]  proxy
     graphiql.js   3.67 MB       1  [emitted]  graphiql
  format.css.map  87 bytes       0  [emitted]  format
 graphiql.js.map   4.41 MB       1  [emitted]  graphiql
graphiql.css.map  89 bytes       1  [emitted]  graphiql
    index.js.map    432 kB       2  [emitted]  index
   index.css.map  86 bytes       2  [emitted]  index
    proxy.js.map   4.46 MB       3  [emitted]  proxy
   proxy.css.map  86 bytes       3  [emitted]  proxy
   [0] multi format 40 bytes {0} [built]
   [0] multi graphiql 52 bytes {1} [built]
   [0] multi index 40 bytes {2} [built]
   [0] multi proxy 52 bytes {3} [built]
    + 661 hidden modules

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./~/style-loader!./~/css-loader!./~/resolve-url-loader!./~/sass-loader?sourceMap!./~/bootstrap-loader/lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/user/projects/project/tmp/graphql-toolbox/~/bootstrap-loader/.bootstraprc-3-default","bootstrapPath":"/Users/ycomb/projects/project/tmp/graphql-toolbox/~/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./~/bootstrap-loader/no-op.js
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:870:18)
    at Object.getInstalledBinaries (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at NormalModule.loadPitch (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:193:17)
    at NormalModule.loadPitch (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.loadPitch (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:186:21)
    at NormalModule.loadPitch (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:223:61)
    at NormalModule.doBuild (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at NormalModule.build (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/user/projects/project/tmp/graphql-toolbox/node_modules/webpack/lib/Compilation.js:126:9)
 @ ./~/bootstrap-loader/lib/bootstrap.loader.js?extractStyles!./~/bootstrap-loader/no-op.js 1:21-1353
Child extract-text-webpack-plugin:
        + 1 hidden modules
    
    ERROR in ENOENT: no such file or directory, scandir '/Users/user/projects/project/tmp/graphql-toolbox/node_modules/node-sass/vendor'
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

And Javascript console claims at http://localhost:9000/graphiql

```
Uncaught Error: Cannot find module "/Users/user/projects/project/tmp/graphql-toolbox/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style!css!resolve-url!sass?sourceMap!./lib/bootstrap.styles.loader.js?{"bootstrapVersion":3,"useCustomIconFontPath":false,"extractStyles":true,"styleLoaders":["style","css","sass"],"styles":["mixins","normalize","print","glyphicons","scaffolding","type","code","grid","tables","forms","buttons","component-animations","dropdowns","button-groups","input-groups","navs","navbar","breadcrumbs","pagination","pager","labels","badges","jumbotron","thumbnails","alerts","progress-bars","media","list-group","panels","wells","responsive-embed","close","modals","tooltip","popovers","carousel","utilities","responsive-utilities"],"scripts":["transition","alert","button","carousel","collapse","dropdown","modal","tooltip","popover","scrollspy","tab","affix"],"configFilePath":"/Users/ycomb/projects/project/tmp/graphql-toolbox/node_modules/bootstrap-loader/.bootstraprc-3-default","bootstrapPath":"/Users/ycomb/projects/project/tmp/graphql-toolbox/node_modules/bootstrap-sass","bootstrapRelPath":"../bootstrap-sass"}!./no-op.js"
    at webpackMissingModule (no-op.js:1)
    at Object.<anonymous> (no-op.js:1)
    at __webpack_require__ (bootstrap 26a3670…?112a:19)
    at Object.<anonymous> (extractStyles.js:1)
    at __webpack_require__ (bootstrap 26a3670…?112a:19)
    at Object.<anonymous> (bootstrap 26a3670…?112a:39)
    at __webpack_require__ (bootstrap 26a3670…?112a:19)
    at bootstrap 26a3670…?112a:39
    at bootstrap 26a3670…?112a:39
```

How to fix that?

**Comment by OlegIlyenko** [comment]
I'm not quite sure what went wrong exactly, but I would suggest you to do the clean retry. I just updated some versions, so maybe it will help:

https://github.com/OlegIlyenko/graphql-toolbox/commit/ba1ead41bbd0afc5fb4a8da65473496408dee231

I can also recommend you to use yarn instead of npm (it's more reliable)

**Comment by alexander-myltsev** [comment]
Works in 76f0a8fe3bc85f2af7daee50c431edd2943dda6e . 👍   for rapid reply. And 👍  for yarn.
